# docker-compose up --build => Haz el build antes del run
# docker-compose up -d => Detached from console
# docker-compose ps => mirar procesos
# docker-compose es local al archivo
# docker-compose -f ruta_archivo => ejecutar otro docker-compose.yaml
# docker-compose logs => ver todolo que saca la aplicaci칩n
# docker-compose stop
# docker-compose rm
# docker-compose down

version: "3.6"

# En ejecuci칩n es los containers, en build las im치genes
services:
  gateway:
    image: ${REGISTRY-solero93}/my-gateway:${TAG-latest}
    build:
      context: ./src/gateway
    ports:
      - 8080:8080
    restart: always

# Se usa por ejemplo en DNS
  votingapp:
    # Mirar si existe REGISTRY, si no, ponle solero93
    image: ${REGISTRY-solero93}/votingapp:${TAG-latest}
    build:
      context: ./src/votingapp-redis
      # Realmente no es necesario, porque ya lo detecta
      dockerfile: ./Dockerfile
    ports:
      - 8085:8080
    environment:
      REDIS: database:63799
  
  database:
    image: redis
    # Es opcional, porque ya est치 mapeado - solo es para que desde fuera de la red interna de los dockers podamos conectarnos
    ports:
        - 6379:6379
  
  votingapp-test:
    image: votingapp-test
    build:
      context: ./test/votingapp
    environment:
      VOTING_URL: http://votingapp:8080/vote